TH_T01/Bai5_63135741/Bai5_63135741/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bai5_63135741.Models
{
    public class EmpModel
    {
        public string EmpID { get; set; }
        public string Name { get; set; }
        public DateTime BirthOfDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public string Avatar { get; set; }
    }
}

TH_T01/Bai5_63135741/Bai5_63135741/Models/MailInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bai5_63135741.Models
{
    public class MailInfo
    {
        public string From { get; set; }
        public string Password { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

TH_T01/Bai5_63135741/Bai5_63135741/Controllers/ChangeBanner_63135741Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai5_63135741.Controllers
{
    public class ChangeBanner_63135741Controller : Controller
    {
        // GET: ChangeBanner_63135741
        public ActionResult ChangeBanner()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangeBanner(HttpPostedFileBase banner)
        {
            string postedFileName =
           System.IO.Path.GetFileName(banner.FileName);
            var path = Server.MapPath("/Images/" + postedFileName);
            banner.SaveAs(path);
            string fSave = Server.MapPath("/banner.txt");
            System.IO.File.WriteAllText(fSave, postedFileName);
            return View();
        }
    }
}

TH_T01/Bai5_63135741/Bai5_63135741/Controllers/DangKy_63135741Controller.cs
using Bai5_63135741.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai5_63135741.Controllers
{
    public class DangKy_63135741Controller : Controller
    {
        // GET: DangKy_63135741
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(HttpPostedFileBase Avatar, EmpModel emp)
        {
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(Avatar.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            Avatar.SaveAs(path);
            string fSave = Server.MapPath("/emp.txt");
            string[] emInfo =
                {emp.EmpID, emp.Name, emp.BirthOfDate.ToShortDateString(),
                emp.Email,emp.Password,emp.Department, postedFileName};
            //Lưu các thông ti vào tập tin emp.txt
            System.IO.File.WriteAllLines(fSave, emInfo);
            //Ghi nhận các thông tin đăng ký để hiện thị trên View Confirm
            ViewBag.EmpID = emInfo[0];
            ViewBag.Name = emInfo[1];
            ViewBag.BirthOfDate = emInfo[2].ToString();
            ViewBag.Email = emInfo[3];
            ViewBag.Password = emInfo[4];
            ViewBag.Department = emInfo[5];
            ViewBag.Avatar = "/Images/" + emInfo[6];
            return View("Confirm");
        }
        public ActionResult Confirm()
        {
            return View();
        }
    }
}

TH_T01/Bai5_63135741/Bai5_63135741/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai5_63135741.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TH_T01/Bai5_63135741/Bai5_63135741/Controllers/SendMail_63135741Controller.cs
using Bai5_63135741.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Bai5_63135741.Controllers
{
    public class SendMail_63135741Controller : Controller
    {
        // GET: SendMail_63135741
        public ActionResult SendMail()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SendMail(MailInfo model)
        {
            MailMessage mail = new MailMessage();
            mail.From = new MailAddress(model.From);
            mail.To.Add(model.To);
            mail.Subject = model.Subject;
            mail.Body = model.Body;
            mail.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential(model.From, model.Password);
            smtp.EnableSsl = true;
            smtp.Send(mail);

            return RedirectToAction("Index");
        }
    }
}

TH_T01/Bai5_63135741/Bai5_63135741/Views/DangKy_63135741/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    <link rel="stylesheet" type="text/css" href="~/Content/StylesConfirm.css">
}

<div class="container">
    <div class="header">
        <h2>THONG TIN THANH VIEN DA DANG KY</h2>
    </div>

    <div class="content">
        <div class="left_content">
            <img id="avt" src="@ViewBag.Avatar" />
        </div>

        <div class="right_content">
            <p>
                Mã số thành viên: @ViewBag.EmpID
            </p>
            <p>
                Tên: @ViewBag.Name
            </p>
            <p>
                Ngày sinh: @ViewBag.BirthOfDate
            </p>
            <p>
                Email: @ViewBag.Email
            </p>
            <p>
                Mật khẩu: @ViewBag.Password
            </p>
            <p>
                Bộ phận: @ViewBag.Department
            </p>
        </div>
    </div>
    @Html.ActionLink("Dang ky lai", "DangKy", null, new { @class = "custom-link" })
</div>

TH_T01/Bai5_63135741/Bai5_63135741/Views/DangKy_63135741/DangKy.cshtml
@model Bai5_63135741.Models.EmpModel

@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    <link rel="stylesheet" type="text/css" href="~/Content/StylesDangKy.css">
}


@using (Html.BeginForm("DangKy", "DangKy_63135741", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="header">
            <h2>THONG TIN THANH VIEN DANG KI</h2>
        </div>

        <div class="content">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.EmpID, "Ma so nhan vien", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EmpID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Name, "Ho ten", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.BirthOfDate, "Ngay sinh", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BirthOfDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BirthOfDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Password, "Mat khau", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Department, "Don vi", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Department, "Avatar", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        <input type="file" , name="avatar" />
                    </div>
                </div>

                <div class="submit">
                    <input id="btn_submit" type="submit" value="Dang Ky" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

TH_T01/Bai5_63135741/Bai5_63135741/Views/SendMail_63135741/SendMail.cshtml
@model Bai5_63135741.Models.MailInfo

@{
    ViewBag.Title = "SendMail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    <link rel="stylesheet" type="text/css" href="~/Content/StylesEmail.css">

}

@using (Html.BeginForm(Html.BeginForm("SendMail", "SendMail_63135741", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>CHUC NANG GUI EMAIL</h2>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.From, "Gui tu email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, "Mat khau", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.To, "Gui den email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, "Tieu de", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, "Noi dung", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gui email" class="btn btn-default" />
            </div>
        </div>
    </div>
}