TH_T01/Bai3_63135741/Bai3_63135741/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bai3_63135741.Models
{
    public class EmpModel
    {
        public string EmpID { get; set; }
        public string Name { get; set; }
        public DateTime BirthOfDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public string Avatar { get; set; }

    }
}

TH_T01/Bai3_63135741/Bai3_63135741/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai3_63135741.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TH_T01/Bai3_63135741/Bai3_63135741/Controllers/NhanVien_63135741Controller.cs
using Bai3_63135741.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai3_63135741.Controllers
{
    public class NhanVien_63135741Controller : Controller
    {
        // GET: NhanVien_63135741
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase Avatar, EmpModel emp)
        {
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(Avatar.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            Avatar.SaveAs(path);
            string fSave = Server.MapPath("/emp.txt");
            string[] emInfo =
                {emp.EmpID, emp.Name, emp.BirthOfDate.ToShortDateString(),
                emp.Email,emp.Password,emp.Department, postedFileName};
            //Lưu các thông ti vào tập tin emp.txt
            System.IO.File.WriteAllLines(fSave, emInfo);
            //Ghi nhận các thông tin đăng ký để hiện thị trên View Confirm
            ViewBag.EmpID = emInfo[0];
            ViewBag.Name = emInfo[1];
            ViewBag.BirthOfDate = emInfo[2].ToString();
            ViewBag.Email = emInfo[3];
            ViewBag.Password = emInfo[4];
            ViewBag.Department = emInfo[5];
            ViewBag.Avatar = "/Images/" + emInfo[6];
            return View("Confirm");
        }
        public ActionResult Confirm()
        {
            return View();
        }

    }
}

TH_T01/Bai3_63135741/Bai3_63135741/Views/NhanVien_63135741/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
    Layout = null;
}

    <div class="container">
        <div class="header">
            <h2>THONG TIN THANH VIEN DA DANG KY</h2>
        </div>

        <div class="content">
            <div class="left_content">
                <img id="avt" src="@ViewBag.Avatar" />
            </div>

            <div class="right_content">
                <p>
                    Mã số thành viên: @ViewBag.EmpID
                </p>
                <p>
                    Tên: @ViewBag.Name
                </p>
                <p>
                    Ngày sinh: @ViewBag.BirthOfDate
                </p>
                <p>
                    Email: @ViewBag.Email
                </p>
                <p>
                    Mật khẩu: @ViewBag.Password
                </p>
                <p>
                    Bộ phận: @ViewBag.Department
                </p>
            </div>
        </div>
    </div>


<style>
    .container {
        font-family: Arial, sans-serif;
        text-align: center;
        max-width: 500px;
        margin: 0 auto;
        background-color: #f0f0f0;
        border: 1px solid #ddd;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .header {
        padding: 5px;
    }

    .content {
        padding: 20px;
    }

    .left_content img {
        width: 200px;
        height: 200px;
        border-radius: 50%;
        margin-bottom: 20px;
    }

    .right_content p {
        display: flex;
        text-align: start;
        font-size: 18px;
        margin: 10px 0;
    }
</style>

TH_T01/Bai3_63135741/Bai3_63135741/Views/NhanVien_63135741/Index.cshtml
@model Bai3_63135741.Models.EmpModel


@using (Html.BeginForm("Index", "NhanVien_63135741", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    Layout = null;

    <div class="container">
        <div class="header">
            <h2>THONG TIN THANH VIEN DANG KI</h2>
        </div>

        <div class="content">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.EmpID, "Ma so nhan vien", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EmpID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Name, "Ho ten", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.BirthOfDate, "Ngay sinh", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BirthOfDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BirthOfDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Password, "Mat khau", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Department, "Don vi", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Department, "Avatar", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        <input type="file" , name="avatar" />
                    </div>
                </div>

                <div class="submit">
                    <input id="btn_submit" type="submit" value="Dang ki" class="btn btn-default" />
                </div>

            </div>
            
        </div>
    </div>

}

<style>
    .container {
        font-family: Arial, sans-serif;
        text-align: center;
        max-width: 500px;
        margin: 0 auto;
        background-color: #f0f0f0;
        border: 1px solid #ddd;
        padding: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .header {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .content {
        font-size:15px;
    }

    .form-control {
        width: 100%;
        height: 40px;
    }

    .form-group {
        display: flex;
        margin-bottom: 20px;
        align-items: center;
    }

    .col-md-2 {
        width: 30%;
        text-align: right;
        padding-right: 20px;
    }

    .col-md-10 {
        width: 70%;
        margin-right: 50px;
    }

    .submit {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    #btn_submit {
        padding: 10px 30px;
        margin: 20px 0;
    }
</style>