TH_T01/Bai2_63135741/Bai2_63135741/Models/SinhVien.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bai2_63135741.Models
{
    public class SinhVien
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Marks { get; set; }
    }
}

TH_T01/Bai2_63135741/Bai2_63135741/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai2_63135741.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TH_T01/Bai2_63135741/Bai2_63135741/Controllers/SinhVien_63135741Controller.cs
using Bai2_63135741.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai2_63135741.Controllers
{
    public class SinhVien_63135741Controller : Controller
    {
        // GET: SinhVien_63135741
        public ActionResult Index()
        {
            return View();
        }

        //SU DUNG REQUEST
        public ActionResult Register1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register1(FormCollection form)
        {
            ViewBag.Id = Request["Id"];
            ViewBag.Name = Request["Name"];
            ViewBag.Marks = Request["Marks"];
            return View("Registered");
        }

        // SU DUNG DOI SO ACTION
        public ActionResult Register2()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register2(string Id, string Name, string Marks)
        {
            ViewBag.Id = Id;
            ViewBag.Name = Name;
            ViewBag.Marks = Marks;
            return View("Registered");
        }

        // SU DUNG FORM COLLECTION
        public ActionResult Register3()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register3(FormCollection form)
        {
            ViewBag.Id = form["Id"];
            ViewBag.Name = form["Name"];
            ViewBag.Marks = form["Marks"];
            return View("Registered");
        }

        public ActionResult Registered()
        {
            return View();
        }

    }
}

TH_T01/Bai2_63135741/Bai2_63135741/Views/SinhVien_63135741/Register1.cshtml
@{
    ViewBag.Title = "Register1";
    Layout = null;
    <link rel="stylesheet" type="text/css" href="~/Content/IndexStyles.css">
}



@using (Html.BeginForm("Register1", "SinhVien_63135741", FormMethod.Post))
{
    <div class="container">
        <div class="header">
            <h2>THONG TIN SINH VIEN</h2>
        </div>
        <div class="content">
            <label for="Id">Ma sinh vien:</label>
            <input type="text" name="Id" /> <br />

            <label for="Name">Ho va ten:</label>
            <input type="text" name="Name" /> <br />

            <label for="Marks">Diem:</label>
            <input type="text" name="Marks" /> <br />

            <input id="btn_submit" type="submit" value="Dang ky" class="btn btn-default" />
        </div>
    </div>
}

TH_T01/Bai2_63135741/Bai2_63135741/Views/SinhVien_63135741/Register2.cshtml
@{
    ViewBag.Title = "Register2";
    Layout = null;
    <link rel="stylesheet" type="text/css" href="~/Content/IndexStyles.css">
}



@using (Html.BeginForm("Register2", "SinhVien_63135741", FormMethod.Post))
{
    <div class="container">
        <div class="header">
            <h2>THONG TIN SINH VIEN</h2>
        </div>
        <div class="content">
            <label for="Id">Ma sinh vien:</label>
            <input type="text" name="Id" /> <br />

            <label for="Name">Ho va ten:</label>
            <input type="text" name="Name" /> <br />

            <label for="Marks">Diem:</label>
            <input type="text" name="Marks" /> <br />

            <input id="btn_submit" type="submit" value="Dang ky" class="btn btn-default" />
        </div>
    </div>
}

TH_T01/Bai2_63135741/Bai2_63135741/Views/SinhVien_63135741/Register3.cshtml
@{
    ViewBag.Title = "Register3";
    Layout = null;
    <link rel="stylesheet" type="text/css" href="~/Content/IndexStyles.css">
}



@using (Html.BeginForm("Register3", "SinhVien_63135741", FormMethod.Post))
{
    <div class="container">
        <div class="header">
            <h2>THONG TIN SINH VIEN</h2>
        </div>
        <div class="content">
            <label for="Id">Ma sinh vien:</label>
            <input type="text" name="Id" /> <br />

            <label for="Name">Ho va ten:</label>
            <input type="text" name="Name" /> <br />

            <label for="Marks">Diem:</label>
            <input type="text" name="Marks" /> <br />

            <input id="btn_submit" type="submit" value="Dang ky" class="btn btn-default" />
        </div>
    </div>
}

TH_T01/Bai2_63135741/Bai2_63135741/Views/SinhVien_63135741/Registered.cshtml
@{
    ViewBag.Title = "Registered";
    Layout = null;
    <link rel="stylesheet" type="text/css" href="~/Content/IndexStyles.css">
}

<div class="container">
    <div class="header">
        <h2>THONG TIN SINH VIEN DA DANG KY</h2>
    </div>

    <div class="content">
        <p><strong>Ma sinh vien:</strong> @ViewBag.Id</p>
        <p><strong>Ho va ten:</strong> @ViewBag.Name</p>
        <p><strong>Diem:</strong> @ViewBag.Marks</p>
        <a href="@Url.Action("Register1", "SinhVien_63135741")"> <input id="btn_submit" type="submit" value="Quay lai" class="btn btn-default" /></a>
        
    </div>
</div>